#!/usr/bin/env bash

BASEDIR=$(dirname "$0")

chosen_router=""
routers_list="wrt1900acv2 wrt610n"

while getopts "r:" opt; do
    case "$opt" in
        r)
            chosen_router=$OPTARG

            if ! [[ " $routers_list " =~ .*\ $chosen_router\ .* ]]; then
                echo "-r must be one of the following values: $routers_list"
                exit 1
            fi
            ;;
    esac
done

if [ -z "$CLEARTEXT_FTI" ]; then
    echo "\$CLEARTEXT_FTI is empty. Please set it with: \`export CLEARTEXT_FTI=fti/xxxxxxx\`"
    exit 2
fi

if [ -z "$HW_ADDRESS" ]; then
    echo "\$HW_ADDRESS is empty. Please set it with: \`export HW_ADDRESS=A1:B2:C3:D4:E5:F6\`"
    exit 2
fi

# ENCODED_FTI=$(echo -n $CLEARTEXT_FTI | xxd  -p)
HW_ADDRESS_WITHOUT_COLONS=$(echo $HW_ADDRESS | sed "s/://g")

scp -O $BASEDIR/$chosen_router*.config root@192.168.1.1:/tmp/
scp -O $BASEDIR/$chosen_router*.nft root@192.168.1.1:/etc/nftables.d/
ssh root@192.168.1.1 "cat /tmp/$chosen_router.network.config | uci -m import network"
# set hardware address on wan.832
ssh root@192.168.1.1 "uci set network.cfg080f15.macaddr='$HW_ADDRESS'"
ssh root@192.168.1.1 "uci set network.wan.sendopts='77:2b46535644534c5f6c697665626f782e496e7465726e65742e736f66746174686f6d652e4c697665626f7836 90:$ENCODED_FTI'"
ssh root@192.168.1.1 "uci set network.wan.clientid='01$HW_ADDRESS_WITHOUT_COLONS'"
ssh root@192.168.1.1 "uci set network.wan6.sendopts='11:$ENCODED_FTI 15:FSVDSL_livebox.Internet.softathome.Livebox6 16:0000040e0005736167656d 17:000005580006000e495056365f524551554553544544'"
ssh root@192.168.1.1 "uci set network.wan6.clientid='00030001$HW_ADDRESS_WITHOUT_COLONS'"
ssh root@192.168.1.1 "uci commit"
echo "Installation completed. Your router is now rebooting..." && ssh root@192.168.1.1 "reboot"
