#!/usr/bin/env bash

BASEDIR=$(dirname "$0")

chosen_router=""
routers_list="wrt1900acv2 wrt610n"

while getopts "r:" opt; do
    case "$opt" in
        r)
            chosen_router=$OPTARG

            if ! [[ " $routers_list " =~ .*\ $chosen_router\ .* ]]; then
                echo "-r must be one of the following values: $routers_list"
                exit 1
            fi
            ;;
    esac
done

if [ -z "$CLEARTEXT_FTI" ]; then
    echo "\$CLEARTEXT_FTI is empty. Please set it with: \`export CLEARTEXT_FTI=fti/xxxxxxx\`"
    exit 2
fi

ENCODED_FTI=$(echo -n $CLEARTEXT_FTI | xxd  -p)

scp $BASEDIR/*.config root@192.168.1.1:/tmp/
ssh root@192.168.1.1 "cat /tmp/$chosen_router.network.config | uci -m import network && uci commit"
ssh root@192.168.1.1 "uci set network.wan.sendopts='0x4D:2b46535644534c5f6c697665626f782e496e7465726e65742e736f66746174686f6d652e4c697665626f7833 0x5a:00000000000000000000001a0900000558010341010d$ENCODED_FTI' && uci commit"
ssh root@192.168.1.1 "uci set network.wan6.sendopts='11:00000000000000000000001a0900000558010341010d$ENCODED_FTI 15:FSVDSL_livebox.Internet.softathome.livebox4 16:0000040e0005736167656d' && uci commit"
echo "Installation completed. Your router is now rebooting..." && ssh root@192.168.1.1 "reboot"
